### PR TITLE
Update shell script with latest changes

### PR DESCRIPTION
**Pull request by hassannesma**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I edited the script

## What did you learn from the changes you have made?
I revised a lot of the commands we learned. I had to redo it a few times so there stuck in my memory for a bit lol 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I was wondering if there were shortcuts to commands that were about doing things inside a directory. For example, to copy all files in a specific directory to another, what is the approach for that?

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I faced many challenges in uploading / committing the changes. This is because I was editing in the main branch. I eventually figured out that I need to be in the assignment-1 branch. 

## How were these changes tested?
On a separate terminal, I used "cat" to make sure that the changes were being reflected in the document. 

## A reference to a related issue in your repository (if applicable)
I do not understand this.

## Checklist
- [ ] I can confirm that my changes are working as intended
Yes? How do I confirm?

### CODE REVIEW

**Comment by monzchan** [comment]
@hassannesma please resolve the conflict and upload the updated version to complete the assignment

**Comment by hassannesma** [comment]
@monzchan Thank you. I think I did? Not sure how to resolve conflicts but I tried my best.

**Comment by monzchan** [comment]
@hassannesma This is the part 2 of the assignment - resolve conflict
image

**Comment by anjali-deshpande-hub** [comment]
Also, 
1. Please enable 'Actions' so that autograder can run on your assignment. 
2. The main branch has diverged from the DSI::main. The assignment.sh file in main branch has your changes. Only assignment.sh file in the assignment branch should have the changes. This can be fixed by following instructions on slack https://uoft-dsi-certificates.slack.com/archives/C07VC7M4PTL/p1732596801781119

**Pull request merged**
